=== MarineA/acupuncture_website/config/SchemaRouting.xsd
<?xml version="1.0" encoding="UTF-8" ?>


<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"> <!-- Mettre la bonne adresse : http://www.w3.org/2001/XMLSchema -->

    <!-- nouveau type pour forcer une chaîne de caractère non vide / -->
    <xsd:simpleType name="StringNonVide">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
            <xsd:pattern value="[a-zA-Z0-9_]+" /> <!-- ^et $ sont implicites et redondants si on les met -->
        </xsd:restriction>
    </xsd:simpleType>

    <!-- nouveau type pour forcer la chaîne de caractère de commencer par '/' pour le path notamment / -->
    <xsd:simpleType name="StringPath">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\/(.)*"/> <!-- Pattern obligeant de commencer par un / -->
        </xsd:restriction>
    </xsd:simpleType>


    <!-- création de l'élément route appelé ensuite dans routing / -->
    <xsd:element name="route">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="path" type="StringPath" default="/" minOccurs="1" />
                <xsd:element name="controller" type="StringNonVide" minOccurs="0"/>
                <xsd:element name="action" type="StringNonVide" minOccurs="0"/>
                <xsd:element name="operation" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                <!-- minOccurs=0 maxOccurs=1 permet d'avoir l'élément 0 ou 1 fois => caractère optionnel -->
                 <xsd:element name="valeur1" type="xsd:string" minOccurs="0" maxOccurs="1"/>
                 <xsd:element name="valeur2" type="xsd:string" minOccurs="0" maxOccurs="1"/>
             </xsd:sequence>
         </xsd:complexType>
     </xsd:element>


    <!-- création de l'élément racine routing / -->
     <xsd:element name="routing" >
         <xsd:complexType>
             <xsd:sequence>
                 <xsd:element ref="route" minOccurs="1" maxOccurs="unbounded" />
                 <!-- minOccurs=1 maxOccurs=unbounded => élément apparaissant une ou une infinité de fois-->
             </xsd:sequence>
         </xsd:complexType>
     </xsd:element>


 </xsd:schema>

=== MarineA/acupuncture_website/config/routing.xml
<?xml version='1.0' standalone='no'?>


<!-- Si on veut enlever le schema pour mettre juste la DTD, enlever la partie
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="SchemaRouting.xsd"
située en paramètre de routing
Et enlever les commentaires de la partie DTD
-->
<!--
<!DOCTYPE routing [
        <!ELEMENT routing (route*)>
        <!ELEMENT route (path, controller, action,operation?,valeur1?, valeur2?)>
        <!ELEMENT path (#PCDATA)>
        <!ELEMENT controller (#PCDATA)>
        <!ELEMENT action (#PCDATA)>
        <!ELEMENT operation (#PCDATA)>
        <!ELEMENT valeur1 (#PCDATA)>
        <!ELEMENT valeur2 (#PCDATA)>
        ]>
-->

<routing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="SchemaRouting.xsd">

    <route>
        <path>/</path>
        <controller>Home</controller>
        <action>home</action>
    </route>

    <route>
        <path>/home</path>
        <controller>Home</controller>
        <action>home</action>
    </route>

    <route>
        <path>/pathologies</path>
        <controller>Patho</controller>
        <action>getPatho</action>
    </route>

    <route>
        <path>/symptomes</path>
        <controller>Symptome</controller>
        <action>getSymptome</action>
    </route>
    
    <route>
        <path>/connexion</path>
        <controller>Session</controller>
        <action>connexion</action>
    </route>
    
    <route>
        <path>/inscription_form</path>
        <controller>Session</controller>
        <action>inscription_form</action>
    </route>
    <route>
        <path>/inscription</path>
        <controller>Session</controller>
        <action>inscription</action>
    </route>

    <route>
        <path>/deconnexion</path>
        <controller>Session</controller>
        <action>deconnexion</action>
    </route>

    <route>
        <path>/informations</path>
        <controller>Home</controller>
        <action>getInfos</action>
    </route>

    <route>
        <path>/calculatrice</path>
        <controller>Calculatrice</controller>
        <action>descriptionCalculatrice</action>
    </route>

    <route>
        <path>/calculatrice/{operation}/{valeur1}/{valeur2}</path>
        <controller>Calculatrice</controller>
        <action>calcul</action>
        <operation>(addition|soustraction|division|multiplication)</operation>
        <valeur1>(\d+)</valeur1>
        <valeur2>(\d+)</valeur2>
    </route>

</routing>
